### ISSUE TITLE
Please add German translation

### ISSUE THREAD

**Issue by HanSolo72** [SergiuToporjinschi/node-red-contrib-heater-controller#11]
{
    "heater_controller": {
        "label": {
            "size": "Größe",
            "name": "Name",
            "group": "Gruppe",
            "topic": "Topic",
            "slider": "Schieberegler",
            "min": "Min",
            "max": "Max",
            "step": "Schrittweite",
            "unit": "Einheit",
            "celsiusUnit": "Celsius",
            "fahrenheitUnit": "Fahrenheit",
            "kelvinUnit": "Kelvin",
            "hysteresis": "Hysterese",
            "upThreshold": "Oberer Schwellwert",
            "lowerThreshold": "Unterer Schwellwert",
            "calendar": "Kalender"
        },
        "placeholder": {
            "value": "value"
        },
        "error": {
            "no-group": "Gruppe nicht konfiguriert"
        }
    }
}

**Comment by SergiuToporjinschi** [comment]
Please create a fork and ask for pull

**Comment by SergiuToporjinschi** [comment]
Thanks!
