### ISSUE TITLE
Add checkbox 'If msg arrives on input, pass through to output:'

### ISSUE THREAD

**Issue by HanSolo72** [SergiuToporjinschi/node-red-contrib-heater-controller#12]
First, thanks to your great work!

Til now I used the default slider. There is a checkbox **If msg arrives on input, pass through to output:** that avoids endless loops. Please add the same option, because I just created an endless loop.

**Comment by SergiuToporjinschi** [comment]
Hi,
Can you do a fork? I'm not sure what you mean. I will review the changes and I can say if I can merge it.

**Comment by HanSolo72** [comment]
Hi, 
I can't, because I'm not a experienced coder. It's just an enhancement request. I uploaded a screenshot:
https://i.imgur.com/tUPA4tw.png

My problemis: When the target temperature is set from Alexa, I pass the value by topic userTargetValue to the heater node and the heater note sets the target value. That is my endless loop.

**Comment by SergiuToporjinschi** [comment]
I don't have time now, but I will take this in consideration on next release thank you for your idea

**Comment by SergiuToporjinschi** [comment]
@HanSolo72  is already outputting the inserted values but is outputting the entire set.
{"currentTemp":23,"targetValue":22,"isUserCustom":true,"currentSchedule":{"temp":22,"day":"Wednesday","time":"16:40"},"nextSchedule":{"temp":19,"day":"Wednesday","time":"23:59"},"currentHeaterStatus":"off","userTargetValue":22}
check also the schema from the bottom of the readme file.
