### ISSUE TITLE
Hysteresis

### ISSUE THREAD

**Issue by NewYor** [SergiuToporjinschi/node-red-contrib-heater-controller#15]
I don't see any hysteresis or anticipator logic. Any plans for that?

**Comment by NewYor** [comment]
i was looking in the wrong place, nevermind

**Comment by SergiuToporjinschi** [comment]
Hi you can set the Upper/lower threshold in configuration. This means the heater will not start until is the temperature is target + upper and will stop when temperature is target-lower.
This is helping you?
