### ISSUE TITLE
Double click to reset to calendar on iPhone

### ISSUE THREAD

**Issue by HellGL** [SergiuToporjinschi/node-red-contrib-heater-controller#22]
Hi,
is there a way to make the double click to reset to current calendar value work on the iPhone? On most mobile devices double tap zooms in. Maybe a single tab on the current calendar value?

Cheers,
HellG

**Comment by HellGL** [comment]
Just saw that it is also possible to just swipe left or right over the value... Sorry..

**Comment by SergiuToporjinschi** [comment]
@HellGL  yes you can swipe and will rest the value
