### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by jssystemcz** [SergiuToporjinschi/node-red-contrib-heater-controller#24]
Hello, I used heater-controller before and everything was fine. Now I installed on a new RPI and unfortunately in debug writes an error and does not work.
Tested versions of node red: 0.20.7 and 0.17.5
BUG: TypeError: Cannot read property 'push' of undefined
Thank you for your help

**Comment by thucar** [comment]
This seems to be a long persisting issue that has been eluding @SergiuToporjinschi 

I just updated my installation to the latest version, restarted the computer and am still getting the same old error message.

`TypeError: Cannot read property 'push' of undefined`

**Comment by jssystemcz** [comment]
Hello,
after update to node-red 0.20.8. it´s all ok.

**Comment by SergiuToporjinschi** [comment]
Hi @thucar, sorry for late response, I'm working on some other projects... 
I've heard about this but is a problem but I could not reproduce it at all ...
