### ISSUE TITLE
minimal temperature

### ISSUE THREAD

**Issue by floxboy** [SergiuToporjinschi/node-red-contrib-heater-controller#27]
Is it possible to set the temperature below 10C?
maybe you just need to change the variable in one of the files?
I need to burn the basement, and it makes no sense to keep 10C there, 5C is enough

I made a translation into Russian of the node and frontend. where can I send?

**Comment by floxboy** [comment]
Sorry, I figured out how to set the temperature below 10C

but also double click on the iphone does not work. and the slider moves while scrolling. It is very uncomfortable.
but your thermostat is wonderful! thanks for good job!

**Comment by SergiuToporjinschi** [comment]
hi, 
yes double click on heater node in admin, and set slider min and max value :)

**Comment by SergiuToporjinschi** [comment]
unfortunately, I don't have an iphone but once I will get one I will see what I can do
