### ISSUE TITLE
Problem after upgrade to NodeRed V1.0.2

### ISSUE THREAD

**Issue by FlorisHigh3IT** [SergiuToporjinschi/node-red-contrib-heater-controller#29]
After the upgrade the thermostat stopped switching temperatures on the configured times. It shows the correct times and temperatures according to the scheme. But nothing happens.

I cant find any errors in the log or debug window.

**Comment by FlorisHigh3IT** [comment]
After 2 days controller started working again, no clue why..

Closed the issue!

**Comment by SergiuToporjinschi** [comment]
@FlorisHigh3IT mhhh, that's strange... I will update my node-red maybe I will reproduce it
