### ISSUE TITLE
Add screenshot of the UI widget to the README

### ISSUE THREAD

**Issue by johnwalicki** [SergiuToporjinschi/node-red-contrib-heater-controller#3]
Interesting idea!  I need this.  Not certain I want take the time to install it however.  I've hacked up a crude implementation with a bunch of standard Node-RED Dashboard widgets. A screenshot of the Heater Controller UI Widget in the README would be a useful addition to convince me to install it.

**Comment by SergiuToporjinschi** [comment]
Hi @johnwalicki , 
here is a screen shot
![image](https://user-images.githubusercontent.com/9376439/48962464-01874380-ef89-11e8-8210-1b1da8fc5633.png)
and here a testing schema
`[{"id":"e46f3c73.cf7c","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"f41b3621.6bf3b8","type":"inject","z":"e46f3c73.cf7c","name":"currentTemp25","topic":"currentTemp","payload":"25","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":"1","x":160,"y":440,"wires":[["341466f0.92458a"]]},{"id":"9d4d8b48.228078","type":"debug","z":"e46f3c73.cf7c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":650,"y":440,"wires":[]},{"id":"a9453a28.50e1d8","type":"inject","z":"e46f3c73.cf7c","name":"","topic":"currentHeaterStatus","payload":"on","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":480,"wires":[["341466f0.92458a"]]},{"id":"341466f0.92458a","type":"heater-controller","z":"e46f3c73.cf7c","group":"b0258c63.bbce3","name":"t","width":"0","height":"0","sliderMinValue":11,"sliderMaxValue":35,"sliderStep":0.5,"thresholdRising":0.5,"thresholdFalling":0.5,"calendar":"{\n    \"Monday\" : {\n        \"08:00\" : 19,\n        \"00:00\" : 19,\n        \"16:40\" : 22,\n        \"06:20\" : 22,\n        \"23:59\" : 19\n    },\n    \"Tuesday\" : {\n        \"00:00\" : 19,\n        \"06:20\" : 22,\n        \"08:00\" : 19,\n        \"16:40\" : 22,\n        \"23:59\" : 19\n    },\n    \"Wednesday\" : {\n        \"00:00\" : 19,\n        \"06:20\" : 22,\n        \"08:00\" : 19,\n        \"16:40\" : 22,\n        \"23:59\" : 19\n    },\n    \"Thursday\" : {\n        \"00:00\" : 19,\n        \"06:20\" : 22,\n        \"08:00\" : 19,\n        \"16:40\" : 22,\n        \"23:59\" : 19\n    },\n    \"Friday\" : {\n        \"00:00\" : 19,\n        \"06:20\" : 23,\n        \"08:00\" : 19,\n        \"16:40\" : 22,\n        \"23:59\" : 19\n    },\n    \"Saturday\" : {\n        \"00:00\" : 19,\n        \"08:00\" : 20,\n        \"20:00\" : 22,\n        \"23:59\" : 19\n    },\n    \"Sunday\" : {\n        \"00:00\" : 19,\n        \"08:00\" : 20,\n        \"20:00\" : 22,\n        \"23:59\" : 19\n    }\n}","x":470,"y":440,"wires":[["9d4d8b48.228078"]]},{"id":"6eef11a7.aefe7","type":"inject","z":"e46f3c73.cf7c","name":"","topic":"currentHeaterStatus","payload":"off","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":520,"wires":[["341466f0.92458a"]]},{"id":"997fce.a985a03","type":"inject","z":"e46f3c73.cf7c","name":"currentTemp10","topic":"currentTemp","payload":"10","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":160,"y":400,"wires":[["341466f0.92458a"]]},{"id":"124896d5.9a1c49","type":"inject","z":"e46f3c73.cf7c","name":"currentTemp25.5","topic":"currentTemp","payload":"25.5","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":160,"y":560,"wires":[["341466f0.92458a"]]},{"id":"b0258c63.bbce3","type":"ui_group","z":"","name":"Group 1","tab":"e816c0b4.2172d","order":1,"disp":true,"width":"8","collapse":false},{"id":"e816c0b4.2172d","type":"ui_tab","name":"Tab 1","icon":"dashboard","order":1}]`

**Comment by SergiuToporjinschi** [comment]
I just worked on this, I will have also more details in read me files, probably tomorrow.:)

**Comment by johnwalicki** [comment]
Thanks!
