### ISSUE TITLE
Does not fire on schedule

### ISSUE THREAD

**Issue by Vinisz** [SergiuToporjinschi/node-red-contrib-heater-controller#30]
Hi,

Running node-red 1.0.2.
The node does not "fire" on schedule.
All settings look right and if I doubleclick once in the schedule, it does fire and starts heating.
Can you look into this ?

**Comment by ivanovlk** [comment]
Hi Vinisz,

I think node triggers schedule check on input message arrival.
So if no Input messages, no "fire" :)
Usually input message is "currentTemp" topic from a sensor or something.

I'm on 1.0.3 and it works just fine :)

**Comment by Vinisz** [comment]
@ivanovlk , same as the other issue, clear... I will close this one..
