### ISSUE TITLE
UsertargetValue not working

### ISSUE THREAD

**Issue by Vinisz** [SergiuToporjinschi/node-red-contrib-heater-controller#31]
When I send a payload as described to change the temperature, nothing happens.
I tried with the correct topic and some other things, but not working.

{
    "topic" : "userTargetValue",
    "payload" : "20.0"
}

**Comment by ivanovlk** [comment]
Hi Vinisz,

I think node triggers schedule check on input message arrival.
So if no Input messages, no "fire" :)
Usually input message is "currentTemp" topic from a sensor or something.

if no currentTemp topic is received userTargetValue will only update the dashboard.

**Comment by Vinisz** [comment]
Hi @ivanovlk , just checked this and confirmed, it indeeds only fires on message arrival.
I can live with that (just configured my sensors now to send report every 15 minutes, even if there is no change...) 
I think however it is better if at schedule time the module would check the temp at that time...
