### ISSUE TITLE
Suggestion: UI element to identify heater / add heater name

### ISSUE THREAD

**Issue by rhk** [SergiuToporjinschi/node-red-contrib-heater-controller#35]
Awesome widget, I've been collecting same features on the MQTT dashboard on my phone, but this does all of it with just one NR node!

I control 6 heaters within the same dashboard. To be able to identify each heater controller in the dashboard it would be great to be able to add the heater name within the UI widget. Current solution requires a separate text widget.

@SergiuToporjinschi What do you think, would this be useful for others, too? Would it be possible to implement?

**Comment by SergiuToporjinschi** [comment]
Hi @rhk , I'm glad that you like it :);
I think I will do it quite soon.
Nice suggestion, I will add it as optional. 
Thank you for your suggestion!

**Comment by olup** [comment]
Would love this too !

**Comment by SergiuToporjinschi** [comment]
Should be there now.
