### ISSUE TITLE
heater controler still work without sensor. 

### ISSUE THREAD

**Issue by devifast** [SergiuToporjinschi/node-red-contrib-heater-controller#41]
I noticed that after removing the connection to the sensor in node red, heater is still work.
after restart, too.
After restart shows the last temperature that was measured. This indicates that if the sensor fails, the controller will run continuously which is not a good option.
sorry for bad english.

**Comment by SergiuToporjinschi** [comment]
Hi, 
this is not a bug.
See the documentation 

> Inputs
This controller accepts one main input which has to have topic as "currentTemp" and payload needs to be a float The entire control is not functional until this message is received The heater status is recalculated when this message received, or when the user is changing the target temperature.

so if it does not receive anymore any message with currentTemp topic, the entire process is blocked; 
This not does not uses any timeouts. It relays on messages with topic "currentTemp" it calculates the status when it receives the message. No message, no recalculation, process is freezing until next currentTemp is received;

**Comment by devifast** [comment]
AAfter removing the sensor physically, does the controller continue to operate?

**Comment by SergiuToporjinschi** [comment]
What do you mean by removing sensor physically? 
If you remove the sensor I suppose that the message with topic currentTemp is will not come anymore and this node will not send any other messages by it self, it keeps last received temperature so if you want to change the status lower the temperature from dashboard, and it will send the new status based on the new temperature set by you

**Comment by devifast** [comment]
I mean that if the sensor gets physically damaged, it still lights a candle.
The cool thing is how to get around the calendar.

**Comment by SergiuToporjinschi** [comment]
I understand, but I cannot make a difference if your sensor died or is just not the case to switch the status.... 
you can do this but adding a function node before this node, and if the sensor died, then send a message, with topic currentTemp and value +100;
this will make the controller think that there is enough heat and send the an off status;
or you can make that function node to send a similar message like the heater-controller but with status off

**Comment by devifast** [comment]
I'm glad we think the same way, but in the absence of an inlet temperature the controller should be turned off at 100%. now i just pulled the sensor off the board and it still works?

**Comment by devifast** [comment]
I use 18b20 sensor

**Comment by SergiuToporjinschi** [comment]
Does not matter what sensor are you using. 
What's the message that you are sending to this node when the sensor is pulled out,

**Comment by devifast** [comment]
Мога ли да ви изпратя потока да го погледнете?
