### ISSUE TITLE
After removing the sensor, the controller continues to operate.

### ISSUE THREAD

**Issue by devifast** [SergiuToporjinschi/node-red-contrib-heater-controller#42]
After posting issue # 41, my topic was closed after two comments by the author. That is, the controller continues to operate in the absence of a temperature sensor (the sensor is missing physically). This controller behavior causes events that are not good for each user. Imagine stretching a cable with a sensor through your home and your dog biting it, or has the sensor itself come in time? What happens if I rely on it for my tank or heat the water in a boiler? I do not mean to offend the author in any way, but this is unacceptable. This is a forum for discussion and problem solving. I am waiting for an answer. Greetings.

**Comment by devifast** [comment]
At the risk of offending the author, the temperature in big numbers should be the current one and set in the mac section.

**Comment by SergiuToporjinschi** [comment]
I cannot ensure the integrity of your network and your scenario cannot be detected by this node. 
I cannot suppose that a sensor is not working if the message is not coming; you have to take care of receiving the message; letting this as it is you are deciding how often you are sending the temperature to server. if you want to read it only once each year does not matter. This  node will do one thing only. I want to have separation of concern.
About the current temperature in big numbers, you can display it how ever you want without using this node.
Nevertheless, you can, anytime fork this project and do the changes that you want.

**Comment by devifast** [comment]
Thanks for the reply, I'll try to resolve the issue in another way. Greetings.
