### ISSUE TITLE
lock slide bar 

### ISSUE THREAD

**Issue by joergensen70** [SergiuToporjinschi/node-red-contrib-heater-controller#44]
Is there any way to lock the slide bar to avoid that the temperature setpoint is changed by mistake? Using this flow on a dashboard leads into this problem. Trying to scroll is ending in changing the set temperature by mistake.

**Comment by SergiuToporjinschi** [comment]
There is an issue that I cannot fix, unfortunately. see issue #37

**Comment by SergiuToporjinschi** [comment]
The new version has been released, please check on latest version and reopen if is the case
