### ISSUE TITLE
TypeError: Cannot set property 'logs' of undefined

### ISSUE THREAD

**Issue by holgerpieta** [SergiuToporjinschi/node-red-contrib-heater-controller#45]
Current NPM version (2.0.1) throws above error on node-red startup.
Maybe the error happens at other times, too, but I encountered it after restart.

I had a quick look into the code, but couldn't find an obvious culprit, but there have been a lot of commits since 2.0.1.

**Comment by bburkett52** [comment]
I am using version 2.0.1 with Node Red 1.0.3 and it is working great. 

~Bob

**Comment by theWaldschrat** [comment]
I'm running node-red 1.0.4, dunno if that's the reason.

**Comment by davebarrett1959** [comment]
I believe it's because the CurrentTemp has not been set. As soon as this is injected it seems to stop this error.

**Comment by SergiuToporjinschi** [comment]
Hi and sorry for the  delay, but I'm working on this in my spare time.
Is this still an issue?

**Comment by holgerpieta** [comment]
Looks like it's fixed, so let's close this.
