### ISSUE TITLE
Output object not always including payload.currentHeaterStatus

### ISSUE THREAD

**Issue by Medicalmusings** [SergiuToporjinschi/node-red-contrib-heater-controller#52]
Love your module. Exactly what I need.

Using your module to run an aquarium heater via a WIFI plug.
Im taking your current.HeaterStatus and converting to true/false that the wifi plug needs.
All working well.

HOWEVER

Your node, doesn't ALWAYS include payload.currentHeaterStatus in its output.

example 1: Seems if a new temperature comes in and the heater does not have to change state ie switch on/off then the output object doesn't include payload.currentHeaterStatus

example2: Node red is redeployed eg during a code update or reboot of the host computer and temperature is within the hysteresis limits, again payload.currentHeaterStatus is not set in the output object.

Is there any way to **force payload.currentHeaterStatus to be output in the output object** every time a new currentTemp arrives on the input?

Would make using the output of your node far easier to use and much more robust as in the current situation the heater switch can get out of sync with the status that your node is storing internally..

**Comment by SergiuToporjinschi** [comment]
Hi, Sorry for delay but I'm working on this on my spare time. 
For sure there are some bugs, I'm thinking to some major refactoring, I felt the need for having more control without interface.

**Comment by SergiuToporjinschi** [comment]
A new version is released so please check with the latest version and reopen if is the case
