### ISSUE TITLE
fahrenheit support for users in backward countries.  : ) 

### ISSUE THREAD

**Issue by aaronpropst** [SergiuToporjinschi/node-red-contrib-heater-controller#7]
I'd love to be able to change the "C" Labels to "F"   Or just to omit them all together.  I know what units I'm using and the module works just fine otherwise, when fed fahrenheit measurements.

**Comment by SergiuToporjinschi** [comment]
I will add it

**Comment by SergiuToporjinschi** [comment]
Done!
@aaronpropst Wait for node-red flows to be undated to 1.1.6

**Comment by aaronpropst** [comment]
Great! thanks!  
There's a couple more locations that need that Unit value though:
https://github.com/SergiuToporjinschi/node-red-contrib-heater-controller/blob/master/frontEnd.js#L63-L64

**Comment by SergiuToporjinschi** [comment]
:)))) 
@aaronpropst I was so happy that I commit all changes at once and there are no issues :D :D

**Comment by SergiuToporjinschi** [comment]
I published again
