### ISSUE TITLE
Upgrade to 3.0.0 / fail

### ISSUE THREAD

**Issue by rhk3** [SergiuToporjinschi/node-red-contrib-heater-controller#74]
It looks like that new version has been released, YAY!!!

I immediately pushed 'upgrade' and faced this:
![kuva](https://user-images.githubusercontent.com/90139717/132127037-9a7bed37-a99c-4d06-83ba-a8803fd86504.png)
and the node then disappeared breaking my flows.

I was manually able to remove 3.0.0 and after some challenges also was able to reinstall 2.0.2

Waiting for input / new version before trying the upgrade again.

**Comment by SergiuToporjinschi** [comment]
Hi sorry for that, 
I did not checked it on my raspberry, I just removed the version 3.0 from npm and from flow.node-red.
I'm working on it.

**Comment by SergiuToporjinschi** [comment]
Please do not install the new version yet. I will let you know when is ready. I think is related to ECMA6 and probably you will need to update the nodeJS and npm version. By the way what's nodejs version ? I had the same error on 10.x but I developed on 12. now I'm trying with 16 (latest)

**Comment by rhk3** [comment]
rhk@ripapi:~ $ node -v
v10.14.2
rhk@ripapi:~ $ npm -v
6.5.0

node-red version  v0.19.5

**Comment by rhk3** [comment]
Related or not, while trying to downgrade to 2.0.2 these are the messages I got. 

pi@ripapi:~/.node-red/node_modules/node-red-contrib-heater-controller $ npm install node-red-contrib-heater-controller@2.0.2
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "node-red-contrib-heater-controller" under a package
npm ERR! also called "node-red-contrib-heater-controller". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-09-05T11_28_52_842Z-debug.log

Logfile: https://pastebin.com/xQ9NMEX5 (expires in 1 year)


I then had to remove 3.0.0 first (npm uninstall) and then manually reinstall 2.0.2. I still got these errors:
 Refusing to install package with name "node-red-contrib-heater-controller" under a package
npm ERR! also called "node-red-contrib-heater-controller"

but however after npm & system reboot it seems to work..

**Comment by rhk3** [comment]
Indeed I propably should upgrade my Raspberry, still running Stretch with old versions of.. everything..

**Comment by SergiuToporjinschi** [comment]
Hi, 
I think there you have a recursive naming "installing node-red-contrib-heater-controller in node-red-contrib-heater-controller" that's strange, you have to look in the .node-red/node_modules/node-red-contrib-heater-controller there should be direct list of files and not again node-red-contrib-heater-controller. 
here is some gideline how to install latest version of nodejs and npm  on raspberry

https://lindevs.com/install-node-js-and-npm-on-raspberry-pi/

I just finished yesterday to update my raspberry and it works fine now, but you will have to take 3.0.2 if you decide to update your nodejs. 
But for node-red-contrib-heater-controller@>=3.x you will need nodejs at least 12.
Have a nice day!

**Comment by rhk3** [comment]
Awesome, thanks, I'll try later.
