### ISSUE TITLE
TypeError: send is not a function

### ISSUE THREAD

**Issue by rhk3** [SergiuToporjinschi/node-red-contrib-heater-controller#75]
Simple test flow
[{"id":"13fb24db.1b2f3b","type":"ui_heater_controller","z":"b166f006.6ebf68","name":"heater","group":"13ed72f6.2c18e5","unit":"C","displayMode":"buttons","order":5,"width":6,"height":4,"topic":"tempTopic","title":"Heater","logLength":0,"sliderMinValue":10,"sliderMaxValue":35,"sliderStep":0.5,"threshold":0.5,"calendar":"{\n    \"Monday\": {\n        \"00:00\": 19,\n        \"06:20\": 22,\n        \"08:00\": 19,\n        \"16:40\": 22,\n        \"23:59\": 19\n    },\n    \"Tuesday\": {\n        \"00:00\": 19,\n        \"06:20\": 22,\n        \"08:00\": 19,\n        \"16:40\": 22,\n        \"23:59\": 19\n    },\n    \"Wednesday\": {\n        \"00:00\": 19,\n        \"06:20\": 22,\n        \"08:00\": 19,\n        \"16:40\": 22,\n        \"23:59\": 19\n    },\n    \"Thursday\": {\n        \"00:00\": 19,\n        \"06:20\": 22,\n        \"08:00\": 19,\n        \"16:40\": 22,\n        \"23:59\": 19\n    },\n    \"Friday\": {\n        \"00:00\": 19,\n        \"06:20\": 23,\n        \"08:00\": 19,\n        \"16:40\": 22,\n        \"23:59\": 19\n    },\n    \"Saturday\": {\n        \"00:00\": 19,\n        \"08:00\": 20,\n        \"20:00\": 22,\n        \"23:59\": 19\n    },\n    \"Sunday\": {\n        \"00:00\": 19,\n        \"08:00\": 20,\n        \"20:00\": 22,\n        \"23:59\": 19\n    }\n}","x":330,"y":140,"wires":[["a12748a5.44f478"],["5a7ea681.cb0788"]]},{"id":"13ed72f6.2c18e5","type":"ui_group","z":"","name":"Easy1","tab":"b66f2994.7192c8","order":1,"disp":false,"width":"6","collapse":false},{"id":"b66f2994.7192c8","type":"ui_tab","z":"","name":"EasyDash","icon":"dashboard","order":1,"disabled":false,"hidden":false}]

![kuva](https://user-images.githubusercontent.com/90139717/132973160-96c7adb8-b289-4f98-8448-0829e61637d2.png)

However, when pressing the currentTemp, I get debug message from the Heater node: "TypeError: send is not a function" and nothing from the flow outputs is sent.

Heater-controller version 3.0.2
12 Sep 08:57:38 - [info] Node-RED version: v0.19.5   <- I see recommended is 2.0.6.. Do I really have ancient version..?
12 Sep 08:57:38 - [info] Node.js  version: v16.9.1

I'd be happy, if someone could post a simple sample flow with currentTemp and userTargetValue injects to confirm I'm not doing anything wrong & give me sample on how to send values to node. 

I've had 2.x running for quite a while, but can't get anything to work with 3.x

**Comment by rhk3** [comment]
Upgraded to node-red 2.0.6 and seems to work better, I still need to learn how to build a proper userconfig / userTargetValue object..

**Comment by SergiuToporjinschi** [comment]
there are some example schemas here 
https://github.com/SergiuToporjinschi/node-red-contrib-heater-controller/blob/master/TestingFlows.md
in main page (code view) at the bottom of the page "Test schema"
