### ISSUE TITLE
userTargetValue no longer works

### ISSUE THREAD

**Issue by ikidd** [SergiuToporjinschi/node-red-contrib-heater-controller#76]
Had a flow that would feed a userTargetValue on a button click.  Upgraded the control, now clicking a button gives an error "Error: Calling unregistered event: userTargetValue"

Removed node from palette and reinstalled, restarted nodered before and after reinstall, does not seem to fix.

**Comment by SergiuToporjinschi** [comment]
lateste version requirements:
-Requirements for version 3.0.0:
-NodeJS: 16.x Minimum version 12.x
-node-red: 2.0.6 Minimum version 1.x
